os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/tannernelson/raw/install-swift-linux.sh)"
script:
  # Fetch
  - swift package fetch
  - rm -rf Sources/Vapor/Generator
  # Build Vapor
  - swift build --configuration debug
  - swift build --configuration release
  # Test Vapor
  - swift test
