os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/tannernelson/933b2904903ed90481d91dd4c6904aa9/raw/9ff1089cac6e2b740faaa5468061278f6b30eb60/install-swift-linux.sh)"
script:
  # Fetch
  - swift package fetch
  - rm -rf Sources/Vapor/Generator
  # Build Vapor
  - swift build --configuration debug
  - swift build --configuration release
  # Test Vapor
  - swift test
